service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Base Assets Squad by Zlotin

provider: ${file(./serverless-provider.yml)}

plugins:
  - serverless-step-functions

package:
  patterns:
    - "!*"
    - "!*/**"
    - "dist/*"
    - "dist/*/**"

functions:
  writerBSC:
    handler: dist/index.indexerBSC
    fileSystemConfig: ${file(./serverless-fs.yml)}
    timeout: 290
    events:
      - schedule: rate(5 minutes)
  info:
    handler: dist/index.info
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: info
          method: get
          cors: true
  block:
    handler: dist/index.block
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: block/{network}/{date}
          method: get
          cors: true
  transfers:
    handler: dist/index.transfers
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: transfers/{network}/{token}/{date}
          method: get
          cors: true
