service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Base Assets Squad by Zlotin

provider: ${file(./serverless-provider.yml)}

package:
  patterns:
    - "!*"
    - "!*/**"
    - "dist/*"
    - "dist/*/**"

functions:
  indexerBSC:
    handler: dist/index.indexerBSC
    fileSystemConfig: ${file(./serverless-fs.yml)}
    timeout: 100
    events:
      - schedule: rate(2 minutes)
  indexerETH:
    handler: dist/index.indexerETH
    fileSystemConfig: ${file(./serverless-fs.yml)}
    timeout: 100
    events:
      - schedule: rate(2 minutes)
  ping:
    handler: dist/index.ping
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: ping
          method: get
          cors: true
  debug:
    handler: dist/index.debug
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: debug
          method: get
          cors: true
  allTimeLeaders:
    handler: dist/index.allTimeLeaders
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: allTimeLeaders/{network}/{token}
          method: get
          cors: true
