service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Base Assets Squad by Zlotin

provider: ${file(./serverless-provider.yml)}

package:
  patterns:
    - "!*"
    - "!*/**"
    - "dist/*"
    - "dist/*/**"

functions:
  writer:
    handler: dist/index.writer
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - schedule: rate(1 second)
  reader:
    handler: dist/index.reader
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: read/{param}
          method: get
          cors: true
