service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Base Assets Squad by Zlotin

provider: ${file(./serverless-provider.yml)}

plugins:
  - serverless-step-functions

package:
  patterns:
    - "!*"
    - "!*/**"
    - "dist/*"
    - "dist/*/**"

stepFunctions:
  stateMachines:
    writer_wakeup:
      events:
        - schedule: rate(1 minute)
      definition:
        StartAt: Iterator
        States:
          Iterator:
            Type: Task
            Resource:
              Fn::GetAtt: [writer, Arn]
            ResultPath: "$.taskresult"
            Next: IsCountReached
          IsCountReached:
            Type: Choice
            Choices:
              - Variable: "$.taskresult.continue"
                BooleanEquals: true
                Next: Wait
            Default: Done
          Wait:
            Type: Wait
            Seconds: 10
            Next: Iterator
          Done:
            Type: Pass
            End: true

functions:
  writer:
    handler: dist/index.writer
    fileSystemConfig: ${file(./serverless-fs.yml)}
    timeout: 300
  #    events:
  #      - schedule: rate(1 minute)
  reader:
    handler: dist/index.reader
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: read/{param}
          method: get
          cors: true
