service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Base Assets Squad by Zlotin

provider: ${file(./serverless-provider.yml)}

functions:
  writer:
    handler: handler.writer
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - schedule: rate(1 hour)
  reader:
    handler: handler.reader
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: read/{param}
          method: get
          cors: true
