service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Base Assets Squad by Zlotin

provider: ${file(./serverless-provider.yml)}

package:
  patterns:
    - "!*"
    - "!*/**"
    - "dist/*"
    - "dist/*/**"

functions:
  indexerBSC:
    handler: dist/index.indexerBSC
    fileSystemConfig: ${file(./serverless-fs.yml)}
    timeout: 290
    events:
      - schedule: rate(5 minutes)
  ping:
    handler: dist/index.ping
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: ping
          method: get
          cors: true
  info:
    handler: dist/index.info
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: info
          method: get
          cors: true
  transfers:
    handler: dist/index.transfers
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: transfers/{network}/{token}
          method: get
          cors: true
