service: ${env:GITHUB_REPO_NAME}

custom:
  PROJECT: Base Assets Squad by Zlotin

provider: ${file(./serverless-provider.yml)}

plugins:
  - serverless-step-functions

package:
  patterns:
    - "!*"
    - "!*/**"
    - "dist/*"
    - "dist/*/**"


functions:
  writerBSC:
    handler: dist/index.writerBSC
    fileSystemConfig: ${file(./serverless-fs.yml)}
    timeout: 60
    events:
      - schedule: rate(1 minute)
  reader:
    handler: dist/index.reader
    fileSystemConfig: ${file(./serverless-fs.yml)}
    events:
      - http:
          path: read/{param}
          method: get
          cors: true
